user_dir: "/home/jenkins"
app_port: 5000
service:
  workingdir: "{{user_dir}}/django-project/myproject"
  execstart: "{{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application"

djangoservice:
  workingdir: "{{user_dir}}/django-project/myproject"
  execstart: "{{user_dir}}/django-project/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application"



app:
  env:
    SQLALCHEMY_DATABASE_URI: postgresql://demouser:pass123@db01/demodb
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'postgresql://demouser:pass123@db01/demodb'
    DATABASE_ENGINE: 'django.db.backends.postgresql_psycopg2'
    DATABASE_NAME: 'demodb'
    DATABASE_USER: 'demouser'
    DATABASE_PASSWORD: 'pass123'
    DATABASE_HOST: '127.0.0.1'
    DATABASE_PORT: '5432'