---
deployment_server:
  hosts:
    azure_deployment:
      ansible_host: 20.61.41.224
      ansible_port: 22
      ansible_ssh_user: jenkins
  vars:
    ansible_python_interpreter: /usr/bin/python3

